# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url: /
    weight: 20
  - name: 博客
    url: blog/
    weight: 30
  - name: 分类
    url: tags/
    weight: 40
  - name: 杂记
    url: uses/
    weight: 50
